version: '3.9'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-server:
    build:
      context: .
      dockerfile: ./artifacts/api-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://admin:admin123@db:5432/mydb
      CLERK_SECRET_KEY: sk_test_pX336LBADNAzltH2HgwXBojraPKifvCpwPx6xMuFYO
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm --filter @workspace/api-server run dev

  frontend:
    build:
      context: .
      dockerfile: ./artifacts/forceflow/Dockerfile
    ports:
      - "5173:5173"
    environment:
      PORT: 5173
      BASE_PATH: /
      VITE_CLERK_PUBLISHABLE_KEY: pk_test_bGFyZ2UtbWluay01My5jbGVyay5hY2NvdW50cy5kZXYk
      VITE_API_URL: http://localhost:8080
    depends_on:
      - api-server
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm --filter @workspace/forceflow run dev -- --host 0.0.0.0

volumes:
  postgres_data: